export enum Arcanas {
  fool = "Fool",
  magician = "Magician",
  priestess = "Priestess",
  empress = "Empress",
  emperor = "Emperor",
  hierophant = "Hierophant",
  lovers = "Lovers",
  chariot = "Chariot",
  justice = "Justice",
  hermit = "Hermit",
  fortune = "Fortune",
  strength = "Strength",
  hangedMan = "Hanged Man",
  death = "Death",
  temperance = "Temperance",
  devil = "Devil",
  tower = "Tower",
  star = "Star",
  moon = "Moon",
  sun = "Sun",
  judgement = "Judgement",
  aeon = "Aeon",
  world = "World",
}
